site_name: DARC zensical boilerplate
site_url: https://dataresearchcenter.github.io/zensical-theme-darc/
repo_url: https://github.com/dataresearchcenter/zensical-theme-darc

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Components: components.md
  - Typography: typography.md

theme:
  name: material
  custom_dir: docs/overrides
  logo:        https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg
  favicon:     https://cdn.investigativedata.org/style/logos/darc/favicon.ico
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/sun
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/moon
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - content.code.copy

extra_css:
  - https://cdn.investigativedata.org/style/fonts.min.css
  - stylesheets/darc-zensical.css
  - stylesheets/extra.css

extra:
  logo_light: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Pos.svg
  social:
    - icon: lucide/mail
      link: mailto:hi@dataresearchcenter.org
    - icon: lucide/globe
      link: https://dataresearchcenter.org
    - icon: simple/github
      link: https://github.com/dataresearchcenter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/dataresearchcenter/

markdown_extensions:
  - admonition
  - attr_list        # required for { .md-button } syntax + per-element attributes
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
